[package]
name = "selections"
version = "0.0.0"
edition = "2021"
publish = false
description = "Multiselections housekeeping"

[dependencies]
intrusive-collections = "0.9.4"

[dev-dependencies]
pretty_assertions = "1.3.0"
